/**
 * 新車數據
 * 所有 2024 年新上市車型
 */

export const NEW_CARS_DATA = [
  {
    id: 1,
    title: 'Toyota Corolla Cross 2024',
    brand: 'Toyota',
    model: 'Corolla Cross',
    year: 2024,
    price: 899000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '1.8L',
    image: '/logos/Toyota Corolla Cross 2024.png',
    colors: ['黑色', '白色', '藍色'],
    features: ['360度攝像頭', '自動停車', '自適應巡航'],
  },
  {
    id: 2,
    title: 'Toyota RAV4 2024',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2024,
    price: 1099000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '2.5L',
    image: '/logos/Toyota RAV4 2024.png',
    colors: ['銀色', '黑色', '紅色'],
    features: ['安全衛士', '動態軌跡', '越野模式'],
  },
  {
    id: 3,
    title: 'Honda CR-V 2024',
    brand: 'Honda',
    model: 'CR-V',
    year: 2024,
    price: 959000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '1.5L Turbo',
    image: '/logos/Honda CR-V 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['全景天窗', '智能駕駛輔助', '無線充電'],
  },
  {
    id: 4,
    title: 'Honda Accord 2024',
    brand: 'Honda',
    model: 'Accord',
    year: 2024,
    price: 1199000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.5L Turbo',
    image: '/logos/Honda Accord 2024.png',
    colors: ['銀色', '藍色', '黑色'],
    features: ['主動安全', '智能座艙', '運動模式'],
  },
  {
    id: 5,
    title: 'Mazda CX-5 2024',
    brand: 'Mazda',
    model: 'CX-5',
    year: 2024,
    price: 879000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.5L',
    image: '/logos/Mazda CX-5 2024.png',
    colors: ['紅色', '黑色', '銀色'],
    features: ['動感設計', '運動懸架', '高級配置'],
  },
  {
    id: 6,
    title: 'Mazda3 2024',
    brand: 'Mazda',
    model: 'Mazda3',
    year: 2024,
    price: 759000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L',
    image: '/logos/Mazda3 2024.png',
    colors: ['黑色', '紅色', '銀色'],
    features: ['i-Activsense', '人馬一體', '運動底盤'],
  },
  {
    id: 7,
    title: 'BMW 330i 2024',
    brand: 'BMW',
    model: '330i',
    year: 2024,
    price: 2290000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/BMW 330i 2024.png',
    colors: ['黑色', '白色', '藍色'],
    features: ['M Sport套件', '寶馬智連', '運動懸架'],
  },
  {
    id: 8,
    title: 'BMW X3 2024',
    brand: 'BMW',
    model: 'X3',
    year: 2024,
    price: 3190000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/BMW X3 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['越野模式', 'xDrive四驅', '全景天窗'],
  },
  {
    id: 9,
    title: 'Mercedes-Benz A-Class 2024',
    brand: 'Mercedes-Benz',
    model: 'A-Class',
    year: 2024,
    price: 1990000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Mercedes-Benz A-Class 2024.png',
    colors: ['白色', '黑色', '銀色'],
    features: ['AMG套件', '全景天窗', '高級音響'],
  },
  {
    id: 10,
    title: 'Mercedes-Benz C-Class 2024',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2024,
    price: 2490000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Mercedes-Benz C-Class 2024.png',
    colors: ['白色', '黑色', '灰色'],
    features: ['MBUX智能系統', '無線充電', 'AMG外觀'],
  },
  {
    id: 11,
    title: 'Volkswagen Golf 2024',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2024,
    price: 969000,
    type: '掀背車',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.5L TSI',
    image: '/logos/Volkswagen Golf 2024.png',
    colors: ['白色', '黑色', '銀色'],
    features: ['MQB平台', '智能駕駛', '數位儀表'],
  },
  {
    id: 12,
    title: 'Volkswagen Tiguan 2024',
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2024,
    price: 1299000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.4L TSI',
    image: '/logos/Volkswagen Tiguan 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['4Motion四驅', '越野模式', '全景天窗'],
  },
  {
    id: 13,
    title: 'Nissan Altima 2024',
    brand: 'Nissan',
    model: 'Altima',
    year: 2024,
    price: 1099000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.5L',
    image: '/logos/Nissan Altima 2024.png',
    colors: ['白色', '黑色', '銀色'],
    features: ['ProPilot科技', '智能後視鏡', '運動外觀'],
  },
  {
    id: 14,
    title: 'Nissan Qashqai 2024',
    brand: 'Nissan',
    model: 'Qashqai',
    year: 2024,
    price: 1199000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.2L Turbo',
    image: '/logos/Nissan Qashqai 2024.png',
    colors: ['紅色', '黑色', '銀色'],
    features: ['e-Power混合動力', '越野模式', '全景天窗'],
  },
  {
    id: 15,
    title: 'Mitsubishi Outlander 2024',
    brand: 'Mitsubishi',
    model: 'Outlander',
    year: 2024,
    price: 1099000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '2.4L',
    image: '/logos/Mitsubishi Outlander 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['S-AWC四驅', '混合動力', '智能安全'],
  },
  {
    id: 16,
    title: 'Mitsubishi Lancer 2024',
    brand: 'Mitsubishi',
    model: 'Lancer',
    year: 2024,
    price: 799000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.6L',
    image: '/logos/Mitsubishi Lancer 2024.png',
    colors: ['紅色', '黑色', '銀色'],
    features: ['動感外觀', '運動懸架', '時尚設計'],
  },
  {
    id: 17,
    title: 'Ford Mustang 2024',
    brand: 'Ford',
    model: 'Mustang',
    year: 2024,
    price: 2199000,
    type: '跑車',
    fuel: '汽油',
    transmission: '自動',
    engine: '5.0L',
    image: '/logos/Ford Mustang 2024.png',
    colors: ['紅色', '黑色', '銀色'],
    features: ['性能引擎', '運動套件', '數位座艙'],
  },
  {
    id: 18,
    title: 'Ford Explorer 2024',
    brand: 'Ford',
    model: 'Explorer',
    year: 2024,
    price: 1799000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '3.0L EcoBoost',
    image: '/logos/Ford Explorer 2024.png',
    colors: ['黑色', '白色', '灰色'],
    features: ['七座SUV', '越野性能', '聯網科技'],
  },
  {
    id: 19,
    title: 'Lexus LS 2024',
    brand: 'Lexus',
    model: 'LS',
    year: 2024,
    price: 3890000,
    type: '轎車',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '3.5L',
    image: '/logos/Lexus LS 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['豪華內飾', 'Mark Levinson音響', 'Panoramic天窗'],
  },
  {
    id: 20,
    title: 'Lexus RX 2024',
    brand: 'Lexus',
    model: 'RX',
    year: 2024,
    price: 3290000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '3.5L',
    image: '/logos/Lexus RX 2024.png',
    colors: ['黑色', '白色', '珍珠白'],
    features: ['豪華配置', 'Mark Levinson音響', '智能安全'],
  },
  {
    id: 21,
    title: 'Porsche 911 2024',
    brand: 'Porsche',
    model: '911',
    year: 2024,
    price: 5990000,
    type: '跑車',
    fuel: '汽油',
    transmission: '自動',
    engine: '3.0L Turbo',
    image: '/logos/Porsche 911 2024.png',
    colors: ['黑色', '銀色', '紅色'],
    features: ['性能傳奇', 'PDK變速箱', '運動減震'],
  },
  {
    id: 22,
    title: 'Porsche Cayenne 2024',
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2024,
    price: 4290000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '3.0L Turbo',
    image: '/logos/Porsche Cayenne 2024.png',
    colors: ['黑色', '白色', '灰色'],
    features: ['性能SUV', 'Air Suspension', '四驅系統'],
  },
  {
    id: 23,
    title: 'Audi A4 2024',
    brand: 'Audi',
    model: 'A4',
    year: 2024,
    price: 2099000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Audi A4 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['Quattro四驅', 'MMI系統', '運動外觀'],
  },
  {
    id: 24,
    title: 'Audi Q5 2024',
    brand: 'Audi',
    model: 'Q5',
    year: 2024,
    price: 2799000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Audi Q5 2024.png',
    colors: ['黑色', '白色', '銀色'],
    features: ['Quattro四驅', 'Virtual Cockpit', '預測式懸架'],
  },
  {
    id: 25,
    title: 'Tesla Model 3 2024',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    price: 1850000,
    type: '轎車',
    fuel: '電動',
    transmission: '自動',
    engine: '純電',
    image: '/logos/Tesla Model 3 2024.png',
    colors: ['珍珠白', '純黑', '銀色'],
    features: ['超級充電', '自動駕駛', '全景天窗'],
  },
  {
    id: 26,
    title: 'Tesla Model Y 2024',
    brand: 'Tesla',
    model: 'Model Y',
    year: 2024,
    price: 2290000,
    type: 'SUV',
    fuel: '電動',
    transmission: '自動',
    engine: '純電',
    image: '/logos/Tesla Model Y 2024.png',
    colors: ['珍珠白', '純黑', '銀色'],
    features: ['雙電動馬達', '超級充電', '自動駕駛'],
  },
];
