/**
 * 中古車數據
 * 所有 2021-2022 年中古車型
 */

export const USED_CARS_DATA = [
  {
    id: 101,
    title: 'Toyota Corolla Cross 2022',
    brand: 'Toyota',
    model: 'Corolla Cross',
    year: 2022,
    price: 629000,
    mileage: 45000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '1.8L',
    image: '/logos/Toyota Corolla Cross 2024.png',
    city: '台北',
    colors: ['黑色', '白色', '藍色'],
    features: ['360度攝像頭', '自動停車', '自適應巡航'],
  },
  {
    id: 102,
    title: 'Toyota RAV4 2021',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2021,
    price: 749000,
    mileage: 65000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '2.5L',
    image: '/logos/Toyota RAV4 2024.png',
    city: '新北',
    colors: ['銀色', '黑色', '紅色'],
    features: ['安全衛士', '動態軌跡', '越野模式'],
  },
  {
    id: 103,
    title: 'Honda CR-V 2022',
    brand: 'Honda',
    model: 'CR-V',
    year: 2022,
    price: 699000,
    mileage: 52000,
    type: 'SUV',
    fuel: '汽油/混合動力',
    transmission: '自動',
    engine: '1.5L Turbo',
    image: '/logos/Honda CR-V 2024.png',
    city: '台中',
    colors: ['黑色', '白色', '銀色'],
    features: ['全景天窗', '智能駕駛輔助', '無線充電'],
  },
  {
    id: 104,
    title: 'Honda Accord 2021',
    brand: 'Honda',
    model: 'Accord',
    year: 2021,
    price: 799000,
    mileage: 58000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.5L Turbo',
    image: '/logos/Honda Accord 2024.png',
    city: '台中',
    colors: ['銀色', '藍色', '黑色'],
    features: ['主動安全', '智能座艙', '運動模式'],
  },
  {
    id: 105,
    title: 'Mazda CX-5 2022',
    brand: 'Mazda',
    model: 'CX-5',
    year: 2022,
    price: 599000,
    mileage: 48000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.5L',
    image: '/logos/Mazda3 2024.png',
    city: '台南',
    colors: ['紅色', '黑色', '銀色'],
    features: ['動感設計', '運動懸架', '高級配置'],
  },
  {
    id: 106,
    title: 'Mazda3 2021',
    brand: 'Mazda',
    model: 'Mazda3',
    year: 2021,
    price: 499000,
    mileage: 62000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L',
    image: '/logos/Mazda3 2024.png',
    city: '高雄',
    colors: ['黑色', '紅色', '銀色'],
    features: ['i-Activsense', '人馬一體', '運動底盤'],
  },
  {
    id: 107,
    title: 'BMW 330i 2021',
    brand: 'BMW',
    model: '330i',
    year: 2021,
    price: 1490000,
    mileage: 72000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/BMW 330i 2024.png',
    city: '台北',
    colors: ['黑色', '白色', '藍色'],
    features: ['M Sport套件', '寶馬智連', '運動懸架'],
  },
  {
    id: 108,
    title: 'BMW X3 2020',
    brand: 'BMW',
    model: 'X3',
    year: 2020,
    price: 1990000,
    mileage: 85000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/BMW X3 2024.png',
    city: '新北',
    colors: ['黑色', '白色', '銀色'],
    features: ['越野模式', 'xDrive四驅', '全景天窗'],
  },
  {
    id: 109,
    title: 'Mercedes-Benz A-Class 2021',
    brand: 'Mercedes-Benz',
    model: 'A-Class',
    year: 2021,
    price: 1290000,
    mileage: 68000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Mercedes-Benz A-Class 2024.png',
    city: '桃園',
    colors: ['白色', '黑色', '銀色'],
    features: ['AMG套件', '全景天窗', '高級音響'],
  },
  {
    id: 110,
    title: 'Mercedes-Benz C-Class 2020',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2020,
    price: 1590000,
    mileage: 78000,
    type: '轎車',
    fuel: '汽油',
    transmission: '自動',
    engine: '2.0L Turbo',
    image: '/logos/Mercedes-Benz C-Class 2024.png',
    city: '新竹',
    colors: ['白色', '黑色', '灰色'],
    features: ['MBUX智能系統', '無線充電', 'AMG外觀'],
  },
  {
    id: 111,
    title: 'Volkswagen Golf 2022',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2022,
    price: 649000,
    mileage: 45000,
    type: '掀背車',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.5L TSI',
    image: '/logos/Volkswagen Golf 2024.png',
    city: '台中',
    colors: ['白色', '黑色', '銀色'],
    features: ['MQB平台', '智能駕駛', '數位儀表'],
  },
  {
    id: 112,
    title: 'Volkswagen Tiguan 2021',
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2021,
    price: 849000,
    mileage: 55000,
    type: 'SUV',
    fuel: '汽油',
    transmission: '自動',
    engine: '1.4L TSI',
    image: '/logos/Volkswagen Tiguan 2024.png',
    city: '高雄',
    colors: ['黑色', '白色', '銀色'],
    features: ['4Motion四驅', '越野模式', '全景天窗'],
  },
];
